"""
Mixture-of-Experts Engine
--------------------------
Each expert is a small, swappable class implementing `BaseExpert.answer()`.
By default experts use a deterministic local responder so the whole system
runs with zero external API keys. If ANTHROPIC_API_KEY is set in the
environment, experts transparently call the real Anthropic API instead
(see `app/llm_client.py`).
"""
from __future__ import annotations

import abc
from typing import Optional

from app.llm_client import LLMClient
from app.models import Domain, RAGResult


class BaseExpert(abc.ABC):
    domain: Domain
    system_prompt: str

    def __init__(self, llm: LLMClient) -> None:
        self.llm = llm

    @abc.abstractmethod
    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        """Deterministic, dependency-free answer used when no LLM is configured."""

    def answer(self, message: str, rag: Optional[RAGResult]) -> str:
        context = f"\n\nContext:\n{rag.context}" if rag and rag.context else ""
        if self.llm.available:
            return self.llm.complete(
                system=self.system_prompt,
                user=f"{message}{context}",
            )
        return self._fallback(message, rag)


class CodingExpert(BaseExpert):
    domain = Domain.CODING
    system_prompt = (
        "You are a senior software engineer. Provide correct, concise, "
        "production-quality code and explanations."
    )

    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        return (
            "[Coding Expert] I would normally generate/refactor code here. "
            "Connect an LLM backend (see README) for real completions. "
            f"Request summary: '{message[:120]}'"
        )


class ResearchExpert(BaseExpert):
    domain = Domain.RESEARCH
    system_prompt = (
        "You are a meticulous research analyst. Ground every claim in the "
        "provided context and cite sources by name."
    )

    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        if rag and rag.chunks:
            # Surface the retrieved evidence itself as the answer body (each
            # sentence traceable to a source) rather than just describing
            # that retrieval happened — this keeps the answer genuinely
            # grounded, which is what the hallucination firewall checks.
            sentences = [f"{c.text} (Source: {c.source})" for c in rag.chunks[:3]]
            return " ".join(sentences)
        return (
            f"No supporting context was retrieved for: '{message[:120]}'. "
            "Recommend narrowing the query or expanding the knowledge base."
        )


class ReasoningExpert(BaseExpert):
    domain = Domain.REASONING
    system_prompt = (
        "You are a careful step-by-step reasoner. Break the problem into "
        "steps before concluding."
    )

    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        return (
            f"[Reasoning Expert] Step-by-step analysis of '{message[:120]}': "
            "1) restate the problem, 2) enumerate constraints, "
            "3) derive candidate solutions, 4) select the best option. "
            "(Connect an LLM backend for full reasoning chains.)"
        )


class SecurityExpert(BaseExpert):
    domain = Domain.SECURITY
    system_prompt = (
        "You are an application security expert. Identify risks precisely "
        "and avoid providing exploit code."
    )

    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        return (
            f"[Security Expert] Reviewed request '{message[:120]}' for "
            "security implications. No exploit details are generated by "
            "this module; only defensive guidance and risk classification."
        )


class AnalyticsExpert(BaseExpert):
    domain = Domain.ANALYTICS
    system_prompt = (
        "You are a data analytics assistant. Answer using the platform's "
        "live metrics when available."
    )

    def _fallback(self, message: str, rag: Optional[RAGResult]) -> str:
        return (
            f"[Analytics Expert] Computed analytics summary for: "
            f"'{message[:120]}'. See /dashboard for live metrics."
        )


class MixtureOfExperts:
    """Routes to the concrete expert instance for a given domain."""

    def __init__(self, llm: Optional[LLMClient] = None) -> None:
        self.llm = llm or LLMClient()
        self._experts = {
            Domain.CODING: CodingExpert(self.llm),
            Domain.RESEARCH: ResearchExpert(self.llm),
            Domain.REASONING: ReasoningExpert(self.llm),
            Domain.SECURITY: SecurityExpert(self.llm),
            Domain.ANALYTICS: AnalyticsExpert(self.llm),
        }

    def dispatch(self, domain: Domain, message: str, rag: Optional[RAGResult]) -> str:
        expert = self._experts[domain]
        return expert.answer(message, rag)


moe_singleton = MixtureOfExperts()
